namespace WebApplication1.Utils
{
    public static class SeedData
    {
        public static List<string> Top100Tracks => new()
        {
            "Blinding Lights - The Weeknd",
            "Shape of You - Ed Sheeran",
            "Perfect - Ed Sheeran",
            "Save Your Tears - The Weeknd",
            "Someone You Loved - Lewis Capaldi",
            "Starboy - The Weeknd",
            "As It Was - Harry Styles",
            "Sunflower - Post Malone",
            "Sweater Weather - The Neighbourhood",
            "One Dance - Drake",
            "Stay - The Kid Laroi",
            "Dance Monkey - Tones and I",
            "Rockstar - Post Malone",
            "Believer - Imagine Dragons",
            "Lucid Dreams - Juice WRLD",
            "Senorita - Shawn Mendes",
            "God's Plan - Drake",
            "Bohemian Rhapsody - Queen",
            "Levitating - Dua Lipa",
            "Bad Guy - Billie Eilish",
            "Shallow - Lady Gaga",
            "Happier - Marshmello",
            "Thinking Out Loud - Ed Sheeran",
            "Old Town Road - Lil Nas X",
            "Don't Start Now - Dua Lipa",
            "Lovely - Billie Eilish",
            "Rockstar - DaBaby",
            "Watermelon Sugar - Harry Styles",
            "Circles - Post Malone",
            "Memories - Maroon 5",
            "Without Me - Halsey",
            "Timeless - The Weeknd",
            "DtMF - Bad Bunny",
            "BAILE INoLVIDABLE - Bad Bunny",
            "NUEVAYoL - Bad Bunny",
            "Tum Se Hi - Mohit Chauhan",
            "VOY A LLeVARTE PA PR - Bad Bunny",
            "EoO - Bad Bunny",
            "Abracadabra - Lady Gaga",
            "VeLDÁ - Bad Bunny",
            "Sports car - Tate McRae",
            "São Paulo - The Weeknd",
            "like JENNIE - JENNIE",
            "Now We Are Free - Hans Zimmer",
            "Anxiety - Doechii",
            "Te Quería Ver - Alemán",
            "La Plena - W Sound",
            "WELTiTA - Bad Bunny",
            "KLOuFRENS - Bad Bunny",
            "NOKIA - Drake",
            "Wish I Knew You - The Revivalists",
            "SPIDER - GIMS",
            "Pee Loon - Mohit Chauhan",
            "7 DIAS - Gabito Ballesteros",
            "Morena - Neton Vega",
            "Por Esos Ojos - Fuerza Regida",
            "PERFuMITO NUEVO - Bad Bunny",
            "Revolving door - Tate McRae",
            "A chillar a otra parte - Pesado",
            "Busy Woman - Sabrina Carpenter",
            "Cry For Me - The Weeknd",
            "Born Again - LISA",
            "Girl From The North Country - Johnny Cash",
            "Tujhe Bhula Diya - Mohit Chauhan",
            "The Swan - Camille Saint-Saëns",
            "Ojalá que te mueras - Pesado",
            "TATTOO - Tito Double P",
            "M&M - Neton Vega",
            "ExtraL - JENNIE",
            "Loco - Pesado",
            "Dark Thoughts - Lil Tecca",
            "Saari Duniya Jalaa Denge - B Praak",
            "Save the Last Dance for Me - Ben E. King",
            "CAFé CON RON - Bad Bunny",
            "VITAMINA - Jombriel",
            "Real Man - beabadoobee",
            "TURiSTA - Bad Bunny",
            "undressed - sombr",
            "Multo - Cup of Joe",
            "KETU TeCRÉ - Bad Bunny",
            "Mi Mayor Necesidad - Marco Antonio Solís",
            "Tum Ho - Mohit Chauhan",
            "Garam & Madu - Tenxi",
            "BOKeTE - Bad Bunny",
            "I'm The Problem - Morgan Wallen",
            "On the Nature of Daylight - Max Richter",
            "EVIL J0RDAN - Playboi Carti",
            "morena (Bonus Track) - Beéle",
            "RATHER LIE - Playboi Carti",
            "Sorry I'm Here For Someone Else - Benson Boone",
            "Love Hangover - JENNIE",
            "LA MuDANZA - Bad Bunny",
            "The Spirit Of Radio - Rush",
            "DIE TRYING - PARTYNEXTDOOR"
        };
    }
}

